services:
  rabbitmq:
    image: rabbitmq:4.0.9-management
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
  db:
    image: mysql
    restart: on-failure
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: netopia
  api-netopia:
    image: api-netopia
    build:
      context: api-server
      dockerfile: ./Dockerfile
    ports:
      - "${APP_PORT}:8888"
    environment:
      - DB_HOST=tcp(db:3306)
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=netopia
      - RABBIT_MQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/
    depends_on:
      - rabbitmq
      - db
    restart: on-failure
  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
    environment:
      ADMINER_DESIGN: "mvt"
      ADMINER_DEFAULT_SERVER: "db"
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "${SWAGGER_PORT}:8080"
    volumes:
      - ./docs/swagger.yml:/api.yml
    environment:
      SWAGGER_JSON: /api.yml
